config/routes.rb
Blocitoff::Application.routes.draw do
  root to: "todos#index"
  devise_for :users
  resources :todos
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :user

  default_scope { order('created_at DESC') }
  
  require 'date'
  def Todo.delete_all_todos
    Todo.where("created_at <= ?", Time.now - 7.days).destroy_all
  end

  def days_left
    sdate = self.created_at
    sdate.to_i
    maxdate = sdate.to_i + 7.days.to_i
    remaining = maxdate.to_i - Time.now.to_i
    Time.at(remaining).day
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :todos
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  def admin?
   role == 'admin'
  end
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
 
 rescue_from Pundit::NotAuthorizedError do |exception|
  redirect_to root_url, alert: exception.message
   end


   protected
 
   def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) << :name
   end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  def index
    @todos = Todo.all
      authorize @todos
  end

  def show
  end

  def new
    @todo = Todo.new
      authorize @todo
  end

  def edit
    @todo = Todo.find(params[:id])
     authorize @todo
  end

  def create
     @todo = current_user.todos.build(todo_params)
      authorize @todo
     @todo.save!
     redirect_to @todo, notice: 'Your new TODO was saved'
  end
  
  def destroy
    @todo.destroy
    redirect_to todos_path
  end


   private

   def set_todo
    @todo = Todo.find(params[:id])
   end
 
   def todo_params
     params.require(:todo).permit(:description)
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_helper.rb
module TodoHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Todos", todos_path %></li>

      <div class="pull-right user-info">
           <% if current_user %>
             Hello <%= current_user.email %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
           <% else %>
             <%= link_to "Sign In", new_user_session_path %> or 
             <%= link_to "Sign Up", new_user_registration_path %>
           <% end %>
         </div>
    </ul>
    
  <p><%= flash[:notice] if flash[:notice] %></p>

<%= yield %>
</div>
</body>
</html>

app/views/todos/index.html.erb
<center><h1>Blocitoff</h1>
<p>A self-destructing to-do list to keep you focused on the things that really matter.</p></center>
<% if policy(Todo.new).create? %>
<table>
  <thead>
    <tr>
      <th>Title</th>

      <th>Days Left</th>
      <th>Complete</th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td><%= todo.description %></td>
        <td><%= todo.days_left %></td>
        <td><%= link_to 'Destroy', todo, method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

  <%= link_to 'New Todo list', new_todo_path, class: 'btn btn-success' %>
<% end %>
<br>


app/views/todos/new.html.erb
<%= form_for Todo.new do |form| %>
   <%= form.text_field :description, placeholder: 'Description' %>
    <%= form.submit 'Save' %>
 <% end %>

app/views/todos/show.html.erb
<p><b><%= @todo.description %></b></p>